In [4]:
#Dependencies

import pandas as pd 
from pathlib import Path
import 

#Upload CSV

crime_data_load = Path("estimated_crimes_1979_2020.csv")

crime_data = pd.read_csv(crime_data_load)

crime_data

,year,state_abbr,state_name,population,violent_crime,homicide,rape_legacy,rape_revised,robbery,aggravated_assault,property_crime,burglary,larceny,motor_vehicle_theft,caveats,total_crimes
0,1979,NaN,NaN,220099000,1208030,21460,76390.0,NaN,480700,629480,11041500,3327700,6601000,1112800,NaN,24499060
1,1979,AK,Alaska,406000,1994,54,292.0,NaN,445,1203,23193,5616,15076,2501,NaN,50374
2,1979,AL,Alabama,3769000,15578,496,1037.0,NaN,4127,9918,144372,48517,83791,12064,NaN,319900
3,1979,AR,Arkansas,2180000,7984,198,595.0,NaN,1626,5565,70949,21457,45267,4225,NaN,157866
4,1979,AZ,Arizona,2450000,14528,219,1120.0,NaN,4305,8884,177977,48916,116976,12085,NaN,385010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2179,2020,WA,Washington,7693612,22596,301,NaN,2677.0,5183,14435,210223,40167,142657,27399,NaN,465638
2180,2020,WI,Wisconsin,5832655,18861,308,NaN,2020.0,3081,13452,86654,12744,64517,9393,NaN,211030
2181,2020,WV,West Virginia,1784787,6352,117,NaN,832.0,369,5034,24976,4877,17828,2271,NaN,62656
2182,2020,WY,Wyoming,582328,1364,18,NaN,333.0,66,947,9379,1225,7190,964,NaN,21486
2183,2020,NaN,NaN,329484123,1313105,21570,NaN,126430.0,243600,921505,6452038,1035314,4606324,810400,NaN,15530286